### ISSUE TITLE
Twitter feed: Too many login attempts

### ISSUE THREAD

**Issue by devkat** [becompany/scala-social-feed#1]
twitter4j.TwitterException:` 420:Returned by the Search and Trends API when you are being rate limited (https://dev.twitter.com/docs/rate-limiting).
    Returned by the Streaming API:
     Too many login attempts in a short period of time.
     Running too many copies of the same application authenticating with the same account name.
    Exceeded connection limit for user

	at twitter4j.HttpClientImpl.handleRequest(HttpClientImpl.java:164)
	at twitter4j.HttpClientBase.request(HttpClientBase.java:57)
	at twitter4j.HttpClientBase.post(HttpClientBase.java:86)
	at twitter4j.TwitterStreamImpl.getUserStream(TwitterStreamImpl.java:264)
	at twitter4j.TwitterStreamImpl$6.getStream(TwitterStreamImpl.java:236)
	at twitter4j.TwitterStreamImpl$TwitterStreamConsumer.run(TwitterStreamImpl.java:554)

**Comment by devkat** [comment]
Fixed by removing twitter4j.
